alter table public.students add column if not exists alternate_phone text;
alter table public.students add column if not exists college_name text;
alter table public.students add column if not exists current_activity text;
alter table public.students add column if not exists place text;
alter table public.students add column if not exists guardian_relation text;
alter table public.students add column if not exists aadhaar_id text;
alter table public.students add column if not exists photo_url text;
alter table public.students add column if not exists aadhaar_document_url text;
alter table public.students add column if not exists lead_source text;
alter table public.students add column if not exists notes text;

alter table public.enrollments add column if not exists pipeline_stage text default 'Enquiry';
alter table public.enrollments add column if not exists lead_date date;
alter table public.enrollments add column if not exists enrolled_date date;
alter table public.enrollments add column if not exists follow_up_date date;
alter table public.enrollments add column if not exists payment_method text;
alter table public.enrollments add column if not exists payment_plan text;
alter table public.enrollments add column if not exists total_fee numeric(12, 2) default 0;
alter table public.enrollments add column if not exists amount_paid numeric(12, 2) default 0;
alter table public.enrollments add column if not exists installments_planned integer default 1;
alter table public.enrollments add column if not exists installments_paid integer default 0;
alter table public.enrollments add column if not exists installment_amount numeric(12, 2) default 0;
alter table public.enrollments add column if not exists next_due_date date;
alter table public.enrollments add column if not exists dropout_reason text;
alter table public.enrollments add column if not exists last_payment_date date;
alter table public.enrollments add column if not exists payment_history jsonb default '[]'::jsonb;
